# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcos/Escuela/Prácticas/2do año/SiGePI/Vista/ui/AgActExamGen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 120)
        Form.setMinimumSize(QtCore.QSize(320, 120))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fecha_selec = QtWidgets.QDateEdit(Form)
        self.fecha_selec.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.fecha_selec.setCalendarPopup(True)
        self.fecha_selec.setObjectName("fecha_selec")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fecha_selec)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.asignatura_selec = QtWidgets.QComboBox(Form)
        self.asignatura_selec.setObjectName("asignatura_selec")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.asignatura_selec)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aceptar_btn = QtWidgets.QPushButton(Form)
        self.aceptar_btn.setObjectName("aceptar_btn")
        self.horizontalLayout_3.addWidget(self.aceptar_btn)
        self.cancelar_btn = QtWidgets.QPushButton(Form)
        self.cancelar_btn.setObjectName("cancelar_btn")
        self.horizontalLayout_3.addWidget(self.cancelar_btn)
        self.clave_btn = QtWidgets.QPushButton(Form)
        self.clave_btn.setObjectName("clave_btn")
        self.horizontalLayout_3.addWidget(self.clave_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Fecha (aaaa/mm/dd):"))
        self.fecha_selec.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.label_2.setText(_translate("Form", "Asignatura:"))
        self.aceptar_btn.setText(_translate("Form", "Aceptar"))
        self.cancelar_btn.setText(_translate("Form", "Cancelar"))
        self.clave_btn.setText(_translate("Form", "Configurar Clave"))
