# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcos/Escuela/Prácticas/2do año/SiGePI/Vista/ui/AgActPregGen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 90)
        Form.setMinimumSize(QtCore.QSize(240, 90))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cal_num = QtWidgets.QDoubleSpinBox(Form)
        self.cal_num.setMaximum(100.0)
        self.cal_num.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.cal_num.setObjectName("cal_num")
        self.horizontalLayout_2.addWidget(self.cal_num)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.aceptar_btn = QtWidgets.QPushButton(Form)
        self.aceptar_btn.setObjectName("aceptar_btn")
        self.horizontalLayout.addWidget(self.aceptar_btn)
        self.cancelar_btn = QtWidgets.QPushButton(Form)
        self.cancelar_btn.setObjectName("cancelar_btn")
        self.horizontalLayout.addWidget(self.cancelar_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Max Calificacion:"))
        self.aceptar_btn.setText(_translate("Form", "Aceptar"))
        self.cancelar_btn.setText(_translate("Form", "Cancelar"))
