# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/marcos/Escuela/Prácticas/2do año/SiGePI/Vista/ui/VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setContentsMargins(200, -1, -1, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gest_est_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gest_est_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.gest_est_btn.setObjectName("gest_est_btn")
        self.verticalLayout.addWidget(self.gest_est_btn)
        self.gest_exam_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gest_exam_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.gest_exam_btn.setMaximumSize(QtCore.QSize(150, 50))
        self.gest_exam_btn.setObjectName("gest_exam_btn")
        self.verticalLayout.addWidget(self.gest_exam_btn)
        self.gest_obj_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gest_obj_btn.setMinimumSize(QtCore.QSize(150, 50))
        self.gest_obj_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gest_obj_btn.setObjectName("gest_obj_btn")
        self.verticalLayout.addWidget(self.gest_obj_btn)
        self.acerca_de_btn = QtWidgets.QPushButton(self.centralwidget)
        self.acerca_de_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.acerca_de_btn.setObjectName("acerca_de_btn")
        self.verticalLayout.addWidget(self.acerca_de_btn)
        self.salir_btn = QtWidgets.QPushButton(self.centralwidget)
        self.salir_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.salir_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.salir_btn.setObjectName("salir_btn")
        self.verticalLayout.addWidget(self.salir_btn)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gest_est_btn.setText(_translate("MainWindow", "Gestionar Estudiantes"))
        self.gest_exam_btn.setText(_translate("MainWindow", "Gestionar Examenes"))
        self.gest_obj_btn.setText(_translate("MainWindow", "Gestionar Objetivos"))
        self.acerca_de_btn.setText(_translate("MainWindow", "Acerca De"))
        self.salir_btn.setText(_translate("MainWindow", "Salir"))
